"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class lcm_monitor_odometer(object):
    __slots__ = ["xLidar", "yLidar", "thetaLidar", "xSE", "ySE", "thetaGyro"]

    __typenames__ = ["float", "float", "float", "float", "float", "float"]

    __dimensions__ = [None, None, None, None, None, None]

    def __init__(self):
        self.xLidar = 0.0
        self.yLidar = 0.0
        self.thetaLidar = 0.0
        self.xSE = 0.0
        self.ySE = 0.0
        self.thetaGyro = 0.0

    def encode(self):
        buf = BytesIO()
        buf.write(lcm_monitor_odometer._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">ffffff", self.xLidar, self.yLidar, self.thetaLidar, self.xSE, self.ySE, self.thetaGyro))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != lcm_monitor_odometer._get_packed_fingerprint():
            raise ValueError("Decode error")
        return lcm_monitor_odometer._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = lcm_monitor_odometer()
        self.xLidar, self.yLidar, self.thetaLidar, self.xSE, self.ySE, self.thetaGyro = struct.unpack(">ffffff", buf.read(24))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if lcm_monitor_odometer in parents: return 0
        tmphash = (0xaa43ec7ff3147ed6) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if lcm_monitor_odometer._packed_fingerprint is None:
            lcm_monitor_odometer._packed_fingerprint = struct.pack(">Q", lcm_monitor_odometer._get_hash_recursive([]))
        return lcm_monitor_odometer._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

