"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class lcm_monitor_odometer(object):
    __slots__ = ["odomLidar", "odomSE", "thetaGyro", "odomCurrent", "currentWayPoint"]

    __typenames__ = ["float", "float", "float", "float", "float"]

    __dimensions__ = [[3], [3], None, [3], [2]]

    def __init__(self):
        self.odomLidar = [ 0.0 for dim0 in range(3) ]
        self.odomSE = [ 0.0 for dim0 in range(3) ]
        self.thetaGyro = 0.0
        self.odomCurrent = [ 0.0 for dim0 in range(3) ]
        self.currentWayPoint = [ 0.0 for dim0 in range(2) ]

    def encode(self):
        buf = BytesIO()
        buf.write(lcm_monitor_odometer._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack('>3f', *self.odomLidar[:3]))
        buf.write(struct.pack('>3f', *self.odomSE[:3]))
        buf.write(struct.pack(">f", self.thetaGyro))
        buf.write(struct.pack('>3f', *self.odomCurrent[:3]))
        buf.write(struct.pack('>2f', *self.currentWayPoint[:2]))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != lcm_monitor_odometer._get_packed_fingerprint():
            raise ValueError("Decode error")
        return lcm_monitor_odometer._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = lcm_monitor_odometer()
        self.odomLidar = struct.unpack('>3f', buf.read(12))
        self.odomSE = struct.unpack('>3f', buf.read(12))
        self.thetaGyro = struct.unpack(">f", buf.read(4))[0]
        self.odomCurrent = struct.unpack('>3f', buf.read(12))
        self.currentWayPoint = struct.unpack('>2f', buf.read(8))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if lcm_monitor_odometer in parents: return 0
        tmphash = (0x91b3c2d6091d67e1) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if lcm_monitor_odometer._packed_fingerprint is None:
            lcm_monitor_odometer._packed_fingerprint = struct.pack(">Q", lcm_monitor_odometer._get_hash_recursive([]))
        return lcm_monitor_odometer._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

